[package]
name = "tools"
version = "0.1.0"
edition = "2021"

[dependencies]
image_hasher = "1.1.2"
image = "0.24.5"
rayon = "1.6.1"
serde_json = "1.0.89"
serde = { version = "1.0.151", features = ["derive"] }
rand = "0.8.5"
serde_yaml = "0.9.19"
anyhow = "1.0.70"
clap = "4.3.0"